# Generated by Django 5.0.3 on 2024-04-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(max_length=100, verbose_name='Цена за покупку'),
        ),
    ]
