# Generated by Django 5.0.3 on 2024-04-06 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата производства продукта'),
        ),
    ]
