# Generated by Django 5.0.3 on 2024-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contactsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('publication_sign', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
