# Generated by Django 5.0.3 on 2024-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactsData',
            new_name='Contacts',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='number_of_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publication_sign',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
