# Generated by Django 4.2.2 on 2024-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('cancellation_of_publication', 'Canceling the publication of the product'), ('changes_the_description', 'Changes the description of any product'), ('changes_the_category', 'Changes the category of any product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='публикация'),
        ),
    ]
